title: Todd Wells
description: Techie type with his feet in the Sierra Nevada Mountains and his head in the cloud

url: http://twellspring.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Tags
   url: /tags

social:
   github: twellspring
   twitter: todd_wells
   #facebook: brianmaierjr
   email: todd@wells.ws

#google_analytics: "UA-58263416-1"
